rootProject.name = "clipping-mcp-server"
include("clipping-app-ports")
include("clipping-api-models")
include("clipping-application-models")
include("clipping-domain")
include("clipping-collection")
include("clipping-user-application")
include("clipping-analytics-application")
include("clipping-digest-application")
include("clipping-engine")
include("clipping-error-types")
include("clipping-notification")
include("clipping-persistence")
include("clipping-pipeline-models")
include("clipping-source")
include("clipping-store-spi")
