import { useState, useRef, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { motion, AnimatePresence } from "framer-motion";
import { PenLine, X, Clock, Hash, Pause, AlertTriangle, Loader2 } from "lucide-react";
import { userKeys } from "@/queries/userKeys";
import { userHistoryKeys } from "@/queries/userHistoryKeys";
import { userService } from "@/services/userService";
import { userHistoryService } from "@/services/userHistoryService";
import type { UserClippingRequest, UserSubscriptionPreference, DeliverySchedule } from "@/types/user";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/shared/EmptyState";
import { CardTitle } from "@/components/shared/CardTitle";
import { MetaDot } from "@/components/shared/MetaDot";
import { userFriendlyMessage } from "@/shared/lib/httpError";
import { formatSlackDestinationLabel } from "@/shared/lib/slackChannel";
import { SubscriptionEditModal } from "./SubscriptionEditModal";
import { PendingRequestDetailModal } from "./PendingRequestDetailModal";

interface EditModalState {
  request: UserClippingRequest;
  preference: UserSubscriptionPreference | null;
}

function deliveryTimeText(schedule: DeliverySchedule): string {
  const DAY_MAP: Record<string, string> = {
    MON: "월",
    TUE: "화",
    WED: "수",
    THU: "목",
    FRI: "금",
    SAT: "토",
    SUN: "일"
  };
  const { preset, deliveryDays, deliveryHour } = schedule;
  const dayPart =
    preset === "WEEKDAYS"
      ? "평일"
      : preset === "EVERYDAY"
        ? "매일"
        : deliveryDays.map((d) => DAY_MAP[d] ?? d).join(",");
  const h = deliveryHour;
  const timePart = h < 12 ? `오전 ${h}시` : h === 12 ? "오후 12시" : `오후 ${h - 12}시`;
  return `${dayPart} ${timePart}`;
}

/** 자동 생성 이름(키워드 나열)인지 확인 — 20자 이상이면 미명명으로 본다 */
function isAutoGeneratedName(name: string): boolean {
  return name.length > 20;
}

const NUDGE_STORAGE_KEY = "clipping-rename-nudge-dismissed";

/** 카드 진입 애니메이션 variants */
const cardVariants = {
  hidden: { opacity: 0, y: 12 },
  visible: { opacity: 1, y: 0 }
};

/** 인라인 이름 편집 전환 애니메이션 */
const nameTransition = { type: "spring" as const, stiffness: 400, damping: 30 };

export function SubscriptionsTab({ requests, onOpenWizard }: { requests: UserClippingRequest[]; onOpenWizard: () => void }) {
  const qc = useQueryClient();
  const [editModal, setEditModal] = useState<EditModalState | null>(null);
  const [loadingPrefFor, setLoadingPrefFor] = useState<string | null>(null);
  const [pendingDetail, setPendingDetail] = useState<UserClippingRequest | null>(null);
  const [renamingId, setRenamingId] = useState<string | null>(null);
  const [renameValue, setRenameValue] = useState("");
  const renameInputRef = useRef<HTMLInputElement>(null);
  const [nudgeDismissed, setNudgeDismissed] = useState(() => {
    try { return localStorage.getItem(NUDGE_STORAGE_KEY) === "true"; } catch { return false; }
  });

  const activeRequests = requests.filter((r) => r.status === "APPROVED");
  const pendingRequests = requests.filter((r) => r.status === "PENDING");
  const subscriptionCount = activeRequests.length + pendingRequests.length;
  const isAtLimit = subscriptionCount >= 5;

  // 이름을 짓지 않은 구독이 있으면 상단 nudge 배너를 보여준다
  const hasUnnamedSubscriptions = activeRequests.some((r) => isAutoGeneratedName(r.requestName));

  const yearMonth = `${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, "0")}`;

  const { data: globalSchedule } = useQuery<DeliverySchedule>({
    queryKey: userKeys.deliverySchedule(),
    queryFn: () => userService.getDeliverySchedule()
  });

  const { data: monthlyStats = [] } = useQuery({
    queryKey: userHistoryKeys.monthlyStats(yearMonth),
    queryFn: () => userHistoryService.getUserMonthlyStats(yearMonth),
    enabled: activeRequests.length > 0
  });

  const { mutate: toggleActive, isPending: isToggling } = useMutation({
    mutationFn: ({ requestId, isActive }: { requestId: string; isActive: boolean }) =>
      userService.updateSubscriptionPreferences(requestId, { isActive }),
    onSuccess: (_, { isActive }) => {
      qc.invalidateQueries({ queryKey: userKeys.clippingRequests() });
      if (isActive) {
        toast.success("구독을 재개했어요");
      } else {
        toast.success("구독을 일시정지했어요");
      }
    },
    onError: (err) => toast.error(userFriendlyMessage(err, "변경하지 못했어요"))
  });

  const { mutate: renameRequest, isPending: isRenaming } = useMutation({
    mutationFn: ({ requestId, name }: { requestId: string; name: string }) =>
      userService.renameClippingRequest(requestId, name),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: userKeys.clippingRequests() });
      setRenamingId(null);
      toast.success("구독 이름을 변경했어요");
    },
    onError: (err) => toast.error(userFriendlyMessage(err, "이름을 변경하지 못했어요"))
  });

  function startRename(req: UserClippingRequest) {
    setRenamingId(req.id);
    setRenameValue(req.requestName);
  }

  function commitRename(requestId: string) {
    const trimmed = renameValue.trim();
    if (!trimmed || trimmed.length > 60) {
      toast.error("이름은 1~60자 이내로 입력해 주세요");
      return;
    }
    renameRequest({ requestId, name: trimmed });
  }

  function cancelRename() {
    setRenamingId(null);
    setRenameValue("");
  }

  function dismissNudge() {
    setNudgeDismissed(true);
    try { localStorage.setItem(NUDGE_STORAGE_KEY, "true"); } catch { /* noop */ }
  }

  // 이름 편집 모드 진입 시 input에 포커스를 맞춘다.
  useEffect(() => {
    if (renamingId && renameInputRef.current) {
      renameInputRef.current.focus();
      renameInputRef.current.select();
    }
  }, [renamingId]);

  async function openEditModal(request: UserClippingRequest) {
    setLoadingPrefFor(request.id);
    try {
      const pref = await userService.getSubscriptionPreferences(request.id);
      setEditModal({ request, preference: pref });
    } catch {
      setEditModal({ request, preference: null });
    } finally {
      setLoadingPrefFor(null);
    }
  }

  const timeText = globalSchedule ? deliveryTimeText(globalSchedule) : null;

  return (
    <>
      <div className="flex items-center justify-between mb-4">
        <p className="text-sm text-muted-foreground">
          {activeRequests.length > 0 ? `${activeRequests.length}개 구독 중` : "구독 중인 뉴스가 없어요"}
        </p>
        <Button size="sm" onClick={() => isAtLimit ? toast("구독 한도(5개)에 도달했어요. 기존 구독을 해제한 후 다시 시도해 주세요.") : onOpenWizard()}>
          + 새 주제
        </Button>
      </div>

      {/* 이름 짓기 Nudge 배너 — 한 번만 노출, 닫으면 localStorage에 저장 */}
      <AnimatePresence>
        {hasUnnamedSubscriptions && !nudgeDismissed && (
          <motion.div
            initial={{ opacity: 0, height: 0, marginBottom: 0 }}
            animate={{ opacity: 1, height: "auto", marginBottom: 16 }}
            exit={{ opacity: 0, height: 0, marginBottom: 0 }}
            transition={{ duration: 0.25, ease: [0.25, 0.1, 0.25, 1] }}
            className="overflow-hidden"
          >
            <div className="relative rounded-2xl bg-gradient-to-r from-secondary to-[var(--status-success-bg)] px-4 py-3">
              <div className="flex items-center gap-3">
                <div className="flex items-center justify-center w-8 h-8 rounded-full bg-primary/10 shrink-0">
                  <PenLine className="h-4 w-4 text-primary" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-foreground">
                    구독에 이름을 지어보세요
                  </p>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    더 쉽게 관리할 수 있어요
                  </p>
                </div>
                <button
                  type="button"
                  onClick={dismissNudge}
                  className="shrink-0 rounded-full p-1 text-muted-foreground hover:text-foreground hover:bg-muted/50 transition-colors"
                  aria-label="닫기"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {pendingRequests.length > 0 && (
        <div className="mb-4 space-y-2">
          <p className="text-xs text-[var(--status-warning-text)] font-medium">
            검토 대기 중 {pendingRequests.length}건
          </p>
          {pendingRequests.map((req) => (
            <button
              key={req.id}
              type="button"
              onClick={() => setPendingDetail(req)}
              className="w-full text-left rounded-xl border border-[var(--status-warning-bg)] bg-[var(--status-warning-bg)] p-3 hover:brightness-95 transition-colors"
            >
              <CardTitle
                size="sm"
                rightSlot={
                  <Badge variant="secondary" className="whitespace-nowrap text-xs">
                    검토 대기
                  </Badge>
                }
              >
                {req.requestName}
              </CardTitle>
              <MetaDot
                className="text-xs text-muted-foreground mt-1"
                items={[req.sourceName, req.personaName]}
              />
            </button>
          ))}
        </div>
      )}

      <PendingRequestDetailModal
        open={!!pendingDetail}
        request={pendingDetail}
        deliveryHour={globalSchedule?.deliveryHour}
        onClose={() => setPendingDetail(null)}
      />

      {activeRequests.length === 0 ? (
        <EmptyState
          title="활성화된 구독이 없어요"
          description="새 주제를 신청하면 관리자 승인 후 뉴스가 발송돼요"
          action={<Button onClick={() => isAtLimit ? toast("구독 한도(5개)에 도달했어요. 기존 구독을 해제한 후 다시 시도해 주세요.") : onOpenWizard()}>1분 만에 시작하기</Button>}
        />
      ) : (
        <motion.div
          className="space-y-3"
          initial="hidden"
          animate="visible"
          transition={{ staggerChildren: 0.06 }}
        >
          {activeRequests.map((req) => {
            const isPaused = req.deliveryState === "PAUSED";
            const reqStats = monthlyStats.filter((s) => s.categoryId === req.approvedCategoryId);
            const totalSent = reqStats.reduce((sum, s) => sum + s.itemsSent, 0);
            const topKeywords = [...new Set(reqStats.flatMap((s) => s.topKeywords))].slice(0, 5);
            const isUnnamed = isAutoGeneratedName(req.requestName);
            const isCurrentlyRenaming = renamingId === req.id;

            return (
              <motion.div
                key={req.id}
                variants={cardVariants}
                transition={{ duration: 0.3, ease: [0.25, 0.1, 0.25, 1] }}
                className="relative"
              >
                <div
                  className={`
                    rounded-2xl bg-card p-4 space-y-3
                    shadow-[var(--shadow-card)]
                    transition-all duration-200 ease-[var(--ease-default)]
                    hover:shadow-[0_4px_16px_rgba(200,130,10,0.08),0_8px_24px_rgba(0,0,0,0.05)]
                    hover:-translate-y-0.5
                    ${isPaused ? "opacity-50 grayscale-[40%]" : ""}
                  `}
                >
                  {/* 일시정지 오버레이 */}
                  {isPaused && (
                    <div className="absolute inset-0 flex items-center justify-center rounded-2xl bg-background/40 z-10 pointer-events-none">
                      <div className="flex items-center gap-1.5 rounded-full bg-muted px-3 py-1.5">
                        <Pause className="h-3.5 w-3.5 text-muted-foreground" />
                        <span className="text-xs font-medium text-muted-foreground">일시정지</span>
                      </div>
                    </div>
                  )}

                  <div className="flex items-start justify-between gap-3">
                    <div className="space-y-2 min-w-0 flex-1">
                      {/* 이름 영역 — 클릭하면 인라인 편집 모드 전환 */}
                      <div className="flex items-center gap-2 flex-wrap">
                        <AnimatePresence mode="wait" initial={false}>
                          {isCurrentlyRenaming ? (
                            <motion.div
                              key="input"
                              initial={{ opacity: 0, scale: 0.98 }}
                              animate={{ opacity: 1, scale: 1 }}
                              exit={{ opacity: 0, scale: 0.98 }}
                              transition={nameTransition}
                              className="flex-1 min-w-0"
                            >
                              <input
                                ref={renameInputRef}
                                type="text"
                                value={renameValue}
                                onChange={(e) => setRenameValue(e.target.value)}
                                onKeyDown={(e) => {
                                  if (e.key === "Enter") commitRename(req.id);
                                  if (e.key === "Escape") cancelRename();
                                }}
                                onBlur={() => {
                                  if (!isRenaming) cancelRename();
                                }}
                                maxLength={60}
                                disabled={isRenaming}
                                placeholder="예: 핀테크 뉴스"
                                className="
                                  font-medium bg-muted/50 rounded-lg border-none outline-none
                                  px-2.5 py-1 text-foreground w-full
                                  ring-1 ring-primary/30 focus:ring-2 focus:ring-primary/50
                                  transition-shadow duration-150
                                "
                              />
                            </motion.div>
                          ) : (
                            <motion.button
                              key="text"
                              initial={{ opacity: 0, scale: 0.98 }}
                              animate={{ opacity: 1, scale: 1 }}
                              exit={{ opacity: 0, scale: 0.98 }}
                              transition={nameTransition}
                              type="button"
                              onClick={() => startRename(req)}
                              className="
                                flex items-center gap-1.5 font-medium text-left
                                group cursor-pointer min-w-0
                              "
                              title="클릭하여 이름 변경"
                            >
                              <span className="truncate">{req.requestName}</span>
                              <PenLine className={`
                                h-3 w-3 shrink-0 transition-all duration-150
                                ${isUnnamed
                                  ? "text-primary/60"
                                  : "text-muted-foreground/0 group-hover:text-muted-foreground/50"
                                }
                              `} />
                            </motion.button>
                          )}
                        </AnimatePresence>

                        {/* 상태 뱃지 */}
                        {req.deliveryState === "ACTION_REQUIRED" && (
                          <Badge variant="destructive" className="text-xs">
                            <AlertTriangle className="h-3 w-3 mr-1" />
                            조치 필요
                          </Badge>
                        )}
                        {req.deliveryState === "VERIFYING_SOURCE" && (
                          <Badge variant="outline" className="text-xs">
                            <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                            연결 확인 중
                          </Badge>
                        )}
                      </div>

                      {/* 메타 정보 pill 칩 */}
                      <div className="flex flex-wrap items-center gap-1.5">
                        {req.slackChannelId && (
                          <span className="inline-flex items-center gap-1 text-xs bg-muted rounded-full px-2.5 py-0.5 text-muted-foreground">
                            <Hash className="h-3 w-3" />
                            {formatSlackDestinationLabel(req.slackChannelId, { genericChannelLabel: "Slack 채널" })}
                          </span>
                        )}
                        {timeText && (
                          <span className="inline-flex items-center gap-1 text-xs bg-muted rounded-full px-2.5 py-0.5 text-muted-foreground">
                            <Clock className="h-3 w-3" />
                            {timeText}
                          </span>
                        )}
                        {reqStats.length > 0 && totalSent > 0 && (
                          <span className="text-xs text-muted-foreground/70 pl-0.5">
                            이번 달 {totalSent}건
                          </span>
                        )}
                      </div>
                    </div>

                    {/* 우측 컨트롤 */}
                    <div className="flex items-center gap-2 shrink-0 relative z-20">
                      <button
                        type="button"
                        role="switch"
                        aria-checked={!isPaused}
                        aria-label={isPaused ? "구독 재개" : "일시정지"}
                        onClick={() => toggleActive({ requestId: req.id, isActive: isPaused })}
                        disabled={isToggling}
                        className={`
                          relative inline-flex h-6 w-11 flex-shrink-0 items-center rounded-full
                          transition-colors duration-200 focus:outline-none disabled:opacity-50
                          ${!isPaused ? "bg-primary" : "bg-muted"}
                        `}
                      >
                        <span
                          className={`
                            inline-block h-4 w-4 transform rounded-full bg-background shadow-sm
                            transition-transform duration-200
                            ${!isPaused ? "translate-x-6" : "translate-x-1"}
                          `}
                        />
                      </button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => openEditModal(req)}
                        disabled={loadingPrefFor === req.id}
                        className="rounded-lg"
                      >
                        {loadingPrefFor === req.id ? "불러오는 중..." : "설정 변경"}
                      </Button>
                    </div>
                  </div>

                  {/* 키워드 칩 */}
                  {topKeywords.length > 0 && (
                    <div className="flex flex-wrap gap-1.5">
                      {topKeywords.map((kw) => (
                        <span key={kw} className="text-xs bg-secondary text-secondary-foreground rounded-full px-2.5 py-0.5">
                          {kw}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              </motion.div>
            );
          })}
        </motion.div>
      )}

      {editModal && (
        <SubscriptionEditModal
          open={true}
          request={editModal.request}
          preference={editModal.preference}
          onClose={() => setEditModal(null)}
        />
      )}
    </>
  );
}
